# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pageview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
