# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dotmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
